### ISSUE TITLE
run instruction

### ISSUE THREAD

**Issue by SohanR** [Joy-Mojumdar/Compiler-Sessional#1]
please provide step-by-step instructions for how can we run lex file in our system in your readme file.

**Comment by novojitdas** [comment]
Thank you for your suggestion. You can also contribute on this repo.

**Comment by SohanR** [comment]
yeah. kindly assign me for this issue. i will open PR soon.

**Comment by novojitdas** [comment]
Assigned you,please check. Thank you for your valuable time.

**Comment by SohanR** [comment]
I created a [PR]( https://github.com/Joy-Mojumdar/Compiler-Sessional/pull/2#issue-1124868741) #2  that satisfied and solves this issue.

kindly review it before merging to the main branch.

**Comment by novojitdas** [comment]
@SohanR Thank you for solving this issue
